[package]
name = "remote_control"
version = "0.1.0"
authors = ["RheoTommy <tommyrheo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[workspace]
members = ["server", "client", "common"]
